### ISSUE TITLE
Set Logging level? [Error Suppression]

### ISSUE THREAD

**Issue by Glatrix** [LavaGang/MelonLoader#129]
For one of the games i am modding, i get a msg "Unable to connect to 127.0.0.1:15881"
I was wondering if there might be a way to suppress this msg.

Usually, if the msg comes from melon loader, it will have [00:00:00.000] before the msg.
or if it comes from a mod, it will have [Mod Name] before, but this error has nothing.

**Comment by HerpDerpinstine** [comment]
That error is with the bHaptics lib that MelonLoader uses.
It means its not connecting to the bHaptics Player.
The issue with it spamming should already be fixed in the next update.
If you don't need bHaptics you can just delete the bHaptics dll in `MelonLoader/Dependencies`.

If you want to suppress any logs from MelonLoader itself there are launch options for that.

**Comment by Glatrix** [comment]
Ok, Thanks
