### ISSUE TITLE
[Question]:  obfuscater,encryption

### ISSUE THREAD

**Issue by orcun9988** [LavaGang/MelonLoader#184]
fixed

**Comment by SlidyDev** [comment]
If you're some who likes to mod game, how bout you don't do it maliciously and make the modding community look bad

**Comment by orcun9988** [comment]
> If you're some who likes to mod games, how bout you don't do it maliciously and make the modding community look bad

I'm not doing this with any bad intentions. for funnier and more pleasant images.

**Comment by loukylor** [comment]
We don't support control flow obfuscation of mods due to security reasons (it would be far easier to distribute viruses this way). Additionally, we do not support the modding Phasmophobia as MelonLoader was main method of modding (and cheating) in Phasmophobia in the past and cheating in multiplayer games is something we do not tolerate nor condone. 

Additionally, trying to hide that you're modding Phasmophobia by deleting screenshots from your issue is not tolerated.

You will not find help here.
