### ISSUE TITLE
[Bug] [CoreCLR]: MelonUtils.GetValidTypes() breaks mod invoking it under Wine

### ISSUE THREAD

**Issue by BowDown097** [LavaGang/MelonLoader#226]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Title explains it all. I have traced down the breakage to specifically lines 223 and 224 in MelonUtils.cs. I am unable to confirm if it also happens in the standard .NET Framework version, but it does 100% happen in the experimental CoreCLR version.
[Latest.log](https://github.com/LavaGang/MelonLoader/files/8477984/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by SamboyCoding** [comment]
@BowDown097 I wasn't able to reproduce your issue because I don't have a wine environment setup, but I've found a probable cause as well as an oversight on my part with regards to how mods are loaded when ML is not running in debug - that latest commit should fix your issue. This link should go live within a couple of minutes for a hopefully fixed build: https://nightly.link/LavaGang/MelonLoader/actions/runs/2160789757

**Comment by SamboyCoding** [comment]
Confirmed fixed in discord
