### ISSUE TITLE
[Bug]: Previous session logs are not being created

### ISSUE THREAD

**Issue by kafeijao** [LavaGang/MelonLoader#477]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Before `6.1` we had the folder `{Game_Directory}\MelonLoader\Logs\` with previous session's logs. But that folder and the logs are not created anymore.

I've tried setting `--melonloader.maxlogs 10` to see if it changed, but still the same. No previous logs.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by Nirv-git** [comment]
I have seem the same behaivor with Melonloader 6.1, no matter the launch options no Log files are saved beyond Lastest.log 
     
           
This is particularly frustrating when someone reports an issue with a mod, but may have restarted their game as part of their troubleshooting. Since the game restarted the Lastest.log file got wiped and any relevant errors that may have been logged are gone.

**Comment by HerpDerpinstine** [comment]
Fixed in v0.6.3
