### ISSUE TITLE
[Enhancement]: Melonloader on mac

### ISSUE THREAD

**Issue by Sans108437** [LavaGang/MelonLoader#636]
### Describe the new feature or enhancement

I really want to download mods on btd6 on my mac I used Wine to download melonloader but melonloader doesnt let me use my mac apps because it turns them to empty files everytime I try to look for something. Can you maybe make a mac version using parallels? its cheaper than buying a macbook and im asking to see if you can launch a mac melonloader so that it can browse mac files and apps.

**Comment by AlphaLovesYou** [comment]
due to many reasons making a apple version of ML is unlikely. there is nobody in the dev team or volunteer team that has access to a mac for the use of testing. we know some individuals have managed to get ML to work on mac with forks of wine which is honestly the best advice i can give. 
also mac development is expensive and a pain in the ass.
