### ISSUE TITLE
[Bug]: melonloader breaks oculus authentication but steam and BepInEx work just fine (il2cpp interop and unhollower)

### ISSUE THREAD

**Issue by Elmishhh** [LavaGang/MelonLoader#654]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

You can launch and play just fine with mods and the mods work but you can't connect to multiplayer, as I wrote in the title this only happens with melonloader and the oculus version of the game 

No errors in the logs, just can't connect to multiplayer 

Game: RUMBLE
it's Il2Cpp

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by slxdy** [comment]
Good, because it's intended (probably by the game developer). The devs of MelonLoader do not support online pvp modding

**Comment by Elmishhh** [comment]
> Good, because it's intended (probably by the game developer). The devs of MelonLoader do not support online pvp modding

it is not intended, there is a modding community and the devs are completely fine unless we cheat (which we dont)

**Comment by slxdy** [comment]
In that case, i doubt its a problem with MelonLoader. However, you can try running MelonLoader in debug mode to check if there are any warnings or if it blocks any of the game server domains

**Comment by slxdy** [comment]
Launch arg `--melonloader.debug`

**Comment by Elmishhh** [comment]
> In that case, i doubt its a problem with MelonLoader. However, you can try running MelonLoader in debug mode to check if there are any warnings or if it blocks any of the game server domains

if it does, is there anything i can do?

**Comment by Elmishhh** [comment]
> In that case, i doubt its a problem with MelonLoader. However, you can try running MelonLoader in debug mode to check if there are any warnings or if it blocks any of the game server domains

it does, how do i unblock it?

**Comment by slxdy** [comment]
What domain is it blocking that the game needs?

**Comment by Elmishhh** [comment]
> What domain is it blocking that the game needs?

it uses azure something something i think

**Comment by slxdy** [comment]
Well yes, but can you check the console logs to see which exact domain it's blocking that the game requires?

**Comment by Elmishhh** [comment]
> Well yes, but can you check the console logs to see which exact domain it's blocking that the game requires?

rumble.azurewebsites.net is one of the blocked websites, as well as the facebook one but i believe you know that wont break networking if it was added

**Comment by slxdy** [comment]
Actually, try running your game with `--melonloader.dab`. This should disable the domain blocker. If this doesn't work for you, then I have no idea

**Comment by Elmishhh** [comment]
> Actually, try running your game with `--melonloader.dab`. This should disable the domain blocker. If this doesn't work for you, then I have no idea

wait whut, melonwiki.xyz says it debugs it not disables it
trying in a bit

**Comment by slxdy** [comment]
Yep, you're totally right. I misread.

I read the source, and honestly, I give up. As much as I love MelonLoader, I'm so tired of the bu*****t MelonLoader blocks and encrypted constants in the source. At this point I just recommend switching to BepInEx, because you won't get much luck with MelonLoader in this case, unless you make a plugin that disables the analytics blocker

**Comment by Elmishhh** [comment]
> Yep, you're totally right. I misread.
> 
> I read the source, and honestly, I give up. As much as I love MelonLoader, I'm so tired of the bu*****t MelonLoader blocks and encrypted constants in the source. At this point I just recommend switching to BepInEx, because you won't get much luck with MelonLoader in this case, unless you make a plugin that disables the analytics blocker

yeah i've been trying to do that exact thing for a while, switching to bepinex simply isnt an option but 0.6.2 is if i can get that mod to work

it sucks but it is what it is

**Comment by Elmishhh** [comment]
ty for trying to help, lets hope my current attempt works

**Comment by HerpDerpinstine** [comment]
> Yep, you're totally right. I misread.
> 
> I read the source, and honestly, I give up. As much as I love MelonLoader, I'm so tired of the bu*****t MelonLoader blocks and encrypted constants in the source. At this point I just recommend switching to BepInEx, because you won't get much luck with MelonLoader in this case, unless you make a plugin that disables the analytics blocker

Nothing in MelonLoader's source is encrypted which you can verify yourself.
The only thing MelonLoader prevents outright is running obfuscated .NET DLLs which is for user safety.

In the case of the issue @Elmishhh is having is that the Analytics Blocker is blocking hosts that were otherwise used for analytical purposes but this specific game actually requires those hosts to function properly.

The Analytics Blocker is in MelonLoader because we receive a lot of complaints from Game Developers when their game sends back logs from modded games.
Additionally a lot of games, and in the case of Unity inside the engine itself, nowadays have analytical systems that syphon a lot of data about the user's every whim.
These are also often left without any actual way for the end user to opt-out or even know of the data collection happening.

However we are discussing if the Analytics Blocker should stay or not in the upcoming MelonLoader Universality update.
For now I can possibly add a disable launch option to the next MelonLoader release.

**Comment by Elmishhh** [comment]
@HerpDerpinstine 
Having a way to disable it would be really nice.
I feel like bunch of things should be added in a text file config like BepInEx (disable the logging console and stuff)

While I'm at this, please make the first launch of an il2cpp game after the initial ML installation not load mods 

We have figured out a temporary solution, it's most likely azurewebsites but no way to really confirm it because testing is rough (I personally don't own the oculus version, only the steam one which doesn't ever connect to Facebook/azurewebsites)

Ty

**Comment by HerpDerpinstine** [comment]
Issues have been fixed in v0.6.3.
