### ISSUE TITLE
[Bug]: Add support for Bonelab Latest Patch #4

### ISSUE THREAD

**Issue by 7kt-swe** [LavaGang/MelonLoader#656]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

 Please add support for Bonelab Latest [Patch #4 ](https://steamcommunity.com/games/1592190/announcements/detail/4175473895131843221?snr=2___)
Store: Steam
Headset: Index

[Latest.log](https://github.com/user-attachments/files/15741106/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by TrevTV** [comment]
This is only an issue on 0.5.7 (Steam only maybe? I don't feel like downloading the Oculus PC version to test)

Community is going to be mostly moving to ML 0.6.1 and 0.6.3 (nightly, available here https://nightly.link/LavaGang/MelonLoader/workflows/build/alpha-development)

Virtually every code mod is broken already due to changes in BL's, so this is probably the best time to update to new ML.

**Comment by 7kt-swe** [comment]
No it's not only an 0.5.7 issue.
I've tried every version available after 0.5.7 and all nightly builds available.

**Comment by TrevTV** [comment]
The only log you provided is for 0.5.7, it's very hard to debug other versions when you don't show what the issue is

**Comment by 7kt-swe** [comment]
> The only log you provided is for 0.5.7, it's very hard to debug other versions when you don't show what the issue is

MelonLoader v0.6..1 log.
[Latest 0.6.1.log](https://github.com/user-attachments/files/15748222/Latest.0.6.1.log)

MelonLoader v0.6.3 log.
[Latest.log](https://github.com/user-attachments/files/15748171/Latest.log)

 I got this when adding missing dependencies:
>     - 'SLZ.Marrow.SDK' v0.0.0.0
>     - 'SLZ.Marrow' v0.0.0.0
>     - 'UnhollowerBaseLib' v0.4.18.0
>     - 'UniTask' v0.0.0.0
> [Latest.0.6.1 test.log](https://github.com/user-attachments/files/15748254/Latest.0.6.1.test.log)
>

The different melonloaders will keep failing no matter what version? since SLZ.SDK was updated to version 0.6 in their latest patch released: Fri, June 7, 2024
So I'm guessing that BoneLib is the cause of crashing?

**Comment by TrevTV** [comment]
Patch 3 (and ML 0.5.7) mods will not work on Patch 4 and 0.6+, so yes, likely Bonelib is breaking stuff on 0.6

**Comment by JTMC-G3** [comment]
Bonelib has not updated for patch 4 and that's why there aren't code mods out. Lakatrazz (fusion founder) stated that he was waiting for bonelib to update before he started work on fusion updates.

**Comment by SamboyCoding** [comment]
To summarise this because I want to close it:
- MelonLoader 0.5.7 won't work on the updated unity version that Bonelab now uses
- MelonLoader 0.6.0 was a breaking change and mods won't work until they're updated
- The code changes in-game were significant enough that mods would have all been broken anyway 
- Due to this, the community has decided to move to 0.6.x, because they can combine 2 major breaking changes and get everyone up to date as it's basically a forced break.
- Mods need to be updated, this needs to be done from the community side, not ours. Please monitor the Bonelab modding discords for information on when that is done.
