### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by CpBEpeuH** [LavaGang/MelonLoader#692]
### Describe the new feature or enhancement

when I install MelonLoader, my antivirus shows viruses. Is this how it should be?
Generated.dll

**Comment by KibblesTheKitten** [comment]
If you have downloaded melonnloader from the official wiki (melonwiki.xyz) then it's just your antivirus being really unhappy with the way melon works, by downloading some files and generating DLLs

**Comment by HerpDerpinstine** [comment]
This is a false positive caused by some Anti-Virus software getting picky about how MelonLoader functions.
MelonLoader is entirely open-source and you can compile it from source if you don't trust the precompiled files.
All we are able to do is submit a request to Anti-Virus software providers asking them to fix the issue.
As a temporary solution you can always just add an exclusion for the MelonLoader folder using your Anti-Virus control panel.
