### ISSUE TITLE
Error Failed to load library!

### ISSUE THREAD

**Issue by Austincraf1** [LavaGang/MelonLoader#694]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [x] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

When I try to open the game with melon loader it just displays "Failed to load library!"
[Latest-Bootstrap.log](https://github.com/user-attachments/files/16237275/Latest-Bootstrap.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by HerpDerpinstine** [comment]
This is an issue with any MelonLoader version before v0.6.4
Please update to the latest version to fix the issue

**Comment by Austincraf1** [comment]
I used 0.6.4 and THAT didnt work, so please tell me what else it could be

**Comment by SNWCreations** [comment]
Same issue occurred on my machine, I solved it by remove all non-ASCII characters in the game path. Is that a possible solution for you?

**Comment by Austincraf1** [comment]
Thank you SO much, I cant believe it worked.
Two things, why does that happen, and second, how can the developers not know about this issue

**Comment by SNWCreations** [comment]
1. This issue is common on the operating systems using different charsets. For example, I'm a Chinese user and I work with Windows that using GBK as the default platform charset. Java programs might also break when they are in paths with special characters (mostly non-ASCII characters)
2. IDK why, maybe the developers only use English when developing.


It is great to hear that my words helped you :D
