### ISSUE TITLE
[Bug]: why?

### ISSUE THREAD

**Issue by RoninRulez** [LavaGang/MelonLoader#733]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [x] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Why did it say, "[ERROR] il2cpp_init detour failed: Failed to load hostfxr. Please make sure you have installed the .NET 6.0 runtime."?

### Did you attach your log file?

Select an option below

**Comment by psyellas** [comment]
because you need to download net 6 runtime, a dependency of melonloader. linked is both x64 or x86 depending on your game, id assume x64 tho
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.33-windows-x64-installer
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.33-windows-x86-installer

**Comment by RoninRulez** [comment]
I did, and it still says it. (x86 btw)

**Comment by HerpDerpinstine** [comment]
That error does not show if you had the proper desktop runtime installed.
